### ISSUE TITLE
Issues with installing terra 

### ISSUE THREAD

**Issue by rbelshe** [rspatial/terra#363]
I am trying to install another package which depends on terra. However, when I try installing terra on R/4.1.0 (as well as other versions of R), I get this error:

```
geos_methods.cpp: In member function 'SpatVector SpatVector::crop(SpatExtent)':
geos_methods.cpp:143:21: error: 'GEOSClipByRect_r' was not declared in this scope
  143 |   GEOSGeometry* r = GEOSClipByRect_r(hGEOSCtxt, g[i].get(), e.xmin, e.ymin, e.xmax, e.ymax);
      |                     ^~~~~~~~~~~~~~~~
geos_methods.cpp: In member function 'SpatVector SpatVector::hull(std::string, std::string)':
geos_methods.cpp:556:7: error: 'GEOSMinimumRotatedRectangle_r' was not declared in this scope
  556 |   h = GEOSMinimumRotatedRectangle_r(hGEOSCtxt, g[0].get());
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
geos_methods.cpp: In member function 'SpatVector SpatVector::voronoi(SpatVector, double, int)':
geos_methods.cpp:573:47: error: expected ';' before 'return'
  573 |  out.setError("GEOS 3.5 required for voronoi")
      |                                               ^
      |                                               ;
  574 |  return out;
      |  ~~~~~~                                        
geos_methods.cpp: In member function 'SpatVector SpatVector::delauny(double, int)':
geos_methods.cpp:633:47: error: expected ';' before 'return'
  633 |  out.setError("GEOS 3.5 required for delauny")
      |                                               ^
      |                                               ;
  634 |  return out;
      |  ~~~~~~                                        
geos_methods.cpp: In member function 'std::vector<double> SpatVector::width()':
geos_methods.cpp:1579:21: error: 'GEOSMinimumWidth_r' was not declared in this scope
 1579 |   GEOSGeometry* w = GEOSMinimumWidth_r(hGEOSCtxt, g[i].get());
      |                     ^~~~~~~~~~~~~~~~~~
geos_methods.cpp: In member function 'std::vector<double> SpatVector::clearance()':
geos_methods.cpp:1602:21: error: 'GEOSMinimumClearanceLine_r' was not declared in this scope
 1602 |   GEOSGeometry* w = GEOSMinimumClearanceLine_r(hGEOSCtxt, g[i].get());
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [geos_methods.o] Error 1
ERROR: compilation failed for package 'terra'
* removing '/packages/7x/R/R-4.1.0/library/terra'
ERROR: dependency 'terra' is not available for package 'rasterVis'
* removing '/packages/7x/R/R-4.1.0/library/rasterVis'

The downloaded source packages are in
        '/tmp/RtmpkWBVMN/downloaded_packages'
Warning messages:
1: In install.packages("rasterVis") :
  installation of package 'terra' had non-zero exit status
2: In install.packages("rasterVis") :
  installation of package 'rasterVis' had non-zero exit status
```

Any help on this would be greatly appreciated. Thank you.

**Comment by rbelshe** [comment]
Ah, my mistake. I saw this and it made me believe that I met the minimum requirements:
`configure: GEOS: 3.4.2
checking GEOS version >= 3.4.0... yes`

I just tried again, per your instructions. It made it farther this time, but has encountered this error:

```
geos_methods.cpp: In member function 'SpatVector SpatVector::hull(std::string, std::string)':
geos_methods.cpp:571:7: error: 'GEOSMinimumRotatedRectangle_r' was not declared in this scope
  571 |   h = GEOSMinimumRotatedRectangle_r(hGEOSCtxt, g[0].get());
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [geos_methods.o] Error 1
ERROR: compilation failed for package 'terra'
* removing '/packages/7x/R/R-4.1.0/library/terra'
Warning message:
In i.p(...) :
  installation of package '/tmp/RtmpN2fRPL/file7d5945a8a52e/terra_1.4-12.tar.gz' had non-zero exit status
```

**Comment by rhijmans** [comment]
> I saw this and it made me believe that I met the minimum requirements:
> configure: GEOS: 3.4.2 checking GEOS version >= 3.4.0... yes

You were right, that is the bare minimum required (even though you loose some functionality).

**Comment by englianhu** [comment]
```r
:~$ sudo su - -c "R -e \"remotes::install_github('rspatial/terra')\""

R version 4.1.3 (2022-03-10) -- "One Push-Up"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> remotes::install_github('rspatial/terra')
Downloading GitHub repo rspatial/terra@HEAD

   checking for file ‘/tmp/RtmpnNl0r3/remotesc3bb4b10a982/rspatial-terra-8c795b0/✔  checking for file ‘/tmp/RtmpnNl0r3/remotesc3bb4b10a982/rspatial-terra-8c795b0/DESCRIPTION’                                                                     
─  preparing ‘terra’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘terra_1.5-27.tar.gz’
   
* installing *source* package ‘terra’ ...
** using staged installation
configure: CC: gcc
configure: CXX: g++ -std=gnu++11
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’
* removing ‘/usr/lib/R/library/terra’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpnNl0r3/filec3bb5a6afbc9/terra_1.5-27.tar.gz’ had non-zero exit status
> 
```
and then try to install `libgdal` relevant missing libraries and works...
```r
:~$ sudo apt install libgdal* -y 
:~$ sudo su - -c "R -e \"remotes::install_github('rspatial/terra')\"" 
...
...
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (terra)
```

```r
:~$ sudo apt install neofetch
:~$ neofetch
            .-/+oossssoo+/-.               englianhu@Scibrokes-Trading 
        `:+ssssssssssssssssss+:`           --------------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.4 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 23-p080d 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.13.0-39-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 3 hours, 50 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 6651 (dpkg), 24 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Plasma 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: KWin 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Sweet-Dark 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Iridescent Lightly 3 [Plasma], 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: BeautyLine [Plasma], BeautyLin 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: konsole 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i5-4590T (4) @ 3.000GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce 710M 
      -+sssssssssssssssssyyyssss+-         GPU: Intel HD Graphics 
        `:+ssssssssssssssssss+:`           Memory: 10201MiB / 15894MiB 
            .-/+oossssoo+/-.
```

**Comment by rhijmans** [comment]
There are instructions here: https://github.com/rspatial/terra

**Comment by mariomack** [comment]
Hi!
I'm still having errors installing terra on Ubuntu Xenial (16.04) - yeah, I know it's a bit old, but could not upgrade yet.
So, just to let you know:
- I've added the ubuntugis ppa repo (unstable);
- installed all _dev_ packages
```
sudo apt-get install libgdal-dev libgeos-dev libproj-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libproj-dev is already the newest version (4.9.2-2).
libgdal-dev is already the newest version (2.2.2+dfsg-1~xenial1).
libgeos-dev is already the newest version (3.5.1-3~xenial0).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
```
- tried to install terra from github repo
Errors:
```
> remotes::install_github("rspatial/terra")
Downloading GitHub repo rspatial/terra@HEAD
✔  checking for file ‘/tmp/RtmpYuI3kI/remotes1f0b36a42cab4/rspatial-terra-2baf658/DESCRIPTION’ (471ms)
─  preparing ‘terra’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts (489ms)
─  checking for empty or unneeded directories
─  building ‘terra_1.6-20.tar.gz’
   
Installing package into ‘/datahome/mario/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package ‘terra’ ...
** using staged installation
configure: CC: gcc -std=gnu99 -std=gnu11
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /usr/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.2.2
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc -std=gnu99 -std=gnu11
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 -std=gnu11 accepts -g... yes
checking for gcc -std=gnu99 -std=gnu11 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -std=gnu11 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/share/gdal/2.2/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 2.2.2
configure: pkg-config proj exists, will use it
checking proj_api.h usability... yes
checking proj_api.h presence... yes
checking for proj_api.h... yes
configure: PROJ: 4.9.2
checking for pj_init_plus in -lproj... yes
checking PROJ: epsg found and readable... yes
checking for geos-config... /usr/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.5.1
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/lib/x86_64-linux-gnu -lgeos_c... yes
configure: Package CPP flags:    -I/usr/include/gdal -I/usr/include
configure: Package LIBS: -lproj     -L/usr/lib -lgdal -L/usr/lib/x86_64-linux-gnu -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
** libs
....
gnu-library/4.1/Rcpp/include'    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c math_utils.cpp -o math_utils.o
geos_methods.cpp:2813:12: error: no declaration matches ‘SpatVector SpatVector::nearest_feature(SpatVector, std::__cxx11::string)’
 SpatVector SpatVector::nearest_feature(SpatVector v, std::string distfun) {
            ^~~~~~~~~~
geos_methods.cpp:2813:12: note: no functions named ‘SpatVector SpatVector::nearest_feature(SpatVector, std::__cxx11::string)’
In file included from geos_spat.h:48,
                 from geos_methods.cpp:19:
spatVector.h:103:7: note: ‘class SpatVector’ defined here
 class SpatVector {
```
One more info: I already have a previous version of terra installed; this error first appeared when I tried to upgrade my packages:
```
> library(terra)
terra 1.5.34
```
Any hint on this?
Tks in advance

**Comment by rhijmans** [comment]
This should work better now. Can you please try again?

**Comment by mariomack** [comment]
Hi @rhijmans ,

Still no success:
```
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/gdal -I/usr/include -I'/datahome/mario/R/x86_64-pc-linux-gnu-library/4.2/Rcpp/include'    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c geosphere.cpp -o geosphere.o
geos_methods.cpp: In member function ‘std::vector<int> SpatVector::nearest_geometry(SpatVector)’:
geos_methods.cpp:2814:9: error: could not convert ‘out’ from ‘SpatVector’ to ‘std::vector<int>’
  return out;
         ^~~
/usr/lib/R/etc/Makeconf:177: recipe for target 'geos_methods.o' failed
make: *** [geos_methods.o] Error 1
make: *** Waiting for unfinished jobs....
ERROR: compilation failed for package ‘terra’
* removing ‘/datahome/mario/R/x86_64-pc-linux-gnu-library/4.2/terra’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmppMuelj/file145251c1a6aa2/terra_1.6-21.tar.gz’ had non-zero exit status
```
Tks again for your help

**Comment by rhijmans** [comment]
sorry ---- I think it works now.

**Comment by mariomack** [comment]
Hi @rhijmans 

 Nothing to apologize ... it compiled and installed smooth now!
 Many thanks!
 Regards

**Comment by msedaghatpour** [comment]
Hello -- I am having issue installing terra too. Any help is appreciated! 

`> install_github("rspatial/terra")
Downloading GitHub repo rspatial/terra@HEAD
── R CMD build ────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/7b/0qg_jy8s75lgzww_sx1szy2h0000gn/T/RtmpGyyinj/remotes40942c6a6e7/rspatial-terra-c133566/DESCRIPTION’ ...
─  preparing ‘terra’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts (768ms)
─  checking for empty or unneeded directories
─  building ‘terra_1.6-49.tar.gz’
   
* installing *source* package ‘terra’ ...
** using staged installation
configure: CC: clang -arch arm64
configure: CXX: clang++ -arch arm64 -std=gnu++11
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/terra’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/7b/0qg_jy8s75lgzww_sx1szy2h0000gn/T//RtmpGyyinj/file4097ff7a9f0/terra_1.6-49.tar.gz’ had non-zero exit status`

**Comment by victoriasilverman** [comment]
I'm trying to install and use the raster package that depends on terra but cannot get terra installed. I tried the usual "install.packages("terra") failed and I tried with remotes as written above in this thread. Error I'm getting is :

configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/terra’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/7b/2lqsdgrs2w78vx71wqf821jm0000gn/T//RtmpJJw6Q0/file2a116c547dc8/terra_1.7-73.tar.gz’ had non-zero exit status

**Comment by 13954380607** [comment]
Hi, I also have the similar issue, could you help me to see? 
remotes::install_github("rspatial/terra")
Downloading GitHub repo rspatial/terra@HEAD
Running `R CMD build`...
* checking for file ‘/tmp/RtmpLWmfdx/remotes2caa4018040337/rspatial-terra-6ebc745/DESCRIPTION’ ... OK
* preparing ‘terra’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘terra_1.7-81.tar.gz’
* installing *source* package ‘terra’ ...
** using staged installation
configure: CC: x86_64-conda-linux-gnu-cc
configure: CXX: x86_64-conda-linux-gnu-c++ -std=gnu++17
checking for gdal-config... /home/dl2373/.conda/envs/r_env/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.9.1
checking GDAL version >= 2.0.1... yes
checking for gcc... x86_64-conda-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether x86_64-conda-linux-gnu-cc accepts -g... yes
checking for x86_64-conda-linux-gnu-cc option to enable C11 features... none needed
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /home/dl2373/.conda/envs/r_env/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available for running:... ERROR 1: PROJ: proj_create_from_database: Open of /home/dl2373/.conda/envs/r_env/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/dl2373/.conda/envs/r_env/share/proj failed
ERROR 1: PROJ: proj_create: unrecognized format / unknown name
ERROR 1: PROJ: proj_create: unrecognized format / unknown name
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ not available?
ERROR: configuration failed for package ‘terra’
* removing ‘/home/dl2373/.conda/envs/r_env/lib/R/library/terra’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpLWmfdx/file2caa40ccea9e6/terra_1.7-81.tar.gz’ had non-zero exit status @rhijmans

**Comment by rhijmans** [comment]
You should be able to use `install.packages("terra")`. If that does not work, it is probably because you are using a very old version of R. In that case, you should update R first.

**Comment by rhijmans** [comment]
If you want to install the development version on Windows, you can do 

```
install.packages('terra', repos='https://rspatial.r-universe.dev')
```

The installation details vary by OS and environment. See the instructions. If it still does not work, it is probably because of something specific to your system and you would need to be very specific about your system to be able to get help. 

You can post on stackoverflow, or start a new issue on this site. Adding different cases to a closed issue does not work very well.

**Comment by P-JuNYeonG** [comment]
Hello, I am also encountering an error during the installation of the terra package, so I am leaving a comment here.
I tried  "install.packages('terra', repos='https://rspatial.r-universe.dev')" 

* installing *source* package 'terra' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

*** arch - i386
rm -f terra.dll RcppExports.o RcppFunctions.o RcppModule.o arith.o crs.o distRaster.o distance.o extract.o file_utils.o focal.o gcp.o gdal_algs.o gdal_multidimensional.o gdalio.o geodesic.o geos_methods.o geosphere.o math_utils.o mediancut.o memory.o movingWindow.o ncdf.o patches.o ram.o raster_methods.o raster_stats.o rasterize.o read.o read_gdal.o read_ogr.o sample.o sort.o spatBase.o spatDataframe.o spatFactor.o spatRaster.o spatRasterMultiple.o spatSources.o spatTime.o spatVector.o spatVector2.o string_utils.o surfArea.o vecmath.o vecmathse.o vector_methods.o watershed_internal.o write.o write_gdal.o write_ogr.o
mkdir -p ../inst
"C:/PROGRA~1/R/R-41~1.2/bin/i386/Rscript.exe" --vanilla "../tools/winlibs.R" 3.4.1
Fatal error: cannot open file '../tools/winlibs.R': No such file or directory

make: *** [Makevars.win:27: winlibs] Error 2
ERROR: compilation failed for package 'terra'
* removing 'C:/Users/zmzm1/Documents/R/win-library/4.1/terra'
Warning in install.packages :
  installation of package ‘terra’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\zmzm1\AppData\Local\Temp\RtmpgP6HGq\downloaded_packages’

**Comment by rhijmans** [comment]
@P-JuNYeonG: you should update R. This only works with a recent version of R.

**Comment by P-JuNYeonG** [comment]
Thx for your advice! @rhijmans

**Comment by Nishantha2006** [comment]
Hi, I'm installing terra with install.packages("terra") on a R 4.3.1 session (OS = RHEL 7.9). I'm running into below error. Could you please advise how to resolve it? Thanks in advance.

> install.packages("terra")
Installing package into ‘/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3’
(as ‘lib’ is unspecified)
trying URL 'https://<sanitised>4242/prod-cran/__linux__/centos7/latest/src/contrib/terra_1.8-15.tar.gz'
Content type 'application/x-gzip' length 1011735 bytes (988 KB)
==================================================
downloaded 988 KB

* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: /opt/rh/devtoolset-12/root/usr/bin/gcc -std=gnu99
configure: CXX: /opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17
checking for gdal-config... /usr/local/bin/gdal244/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.4.4
checking GDAL version >= 2.0.1... yes
checking for gcc... /opt/rh/devtoolset-12/root/usr/bin/gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether /opt/rh/devtoolset-12/root/usr/bin/gcc -std=gnu99 accepts -g... yes
checking for /opt/rh/devtoolset-12/root/usr/bin/gcc -std=gnu99 option to enable C11 features... -std=gnu11
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/local/bin/gdal244/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available for running:... yes
configure: GDAL: 2.4.4
configure: pkg-config proj exists, will use it
checking for proj_api.h... yes
configure: PROJ: 4.8.0
checking for pj_init_plus in -lproj... yes
checking PROJ: epsg found and readable... yes
checking for geos-config... /usr/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.4.2
checking GEOS version >= 3.4.0... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/lib64 -lgeos_c... yes
configure: Package CPP flags:    -I/usr/local/bin/gdal244/include -I/usr/include
configure: Package LIBS: -lproj     -L/usr/local/bin/gdal244/lib -lgdal -L/usr/lib64 -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
** libs
using C compiler: ‘gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)’
using C++ compiler: ‘g++ (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)’
using C++17
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppFunctions.cpp -o RcppFunctions.o
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppModule.cpp -o RcppModule.o
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c arith.cpp -o arith.o
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c crs.cpp -o crs.o
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c distRaster.cpp -o distRaster.o
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c distVector.cpp -o distVector.o
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c distance.cpp -o distance.o
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c extract.cpp -o extract.o
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c file_utils.cpp -o file_utils.o
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c focal.cpp -o focal.o
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gcp.cpp -o gcp.o
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gdal_algs.cpp -o gdal_algs.o
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gdal_multidimensional.cpp -o gdal_multidimensional.o
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gdalio.cpp -o gdalio.o
/opt/rh/devtoolset-12/root/usr/bin/gcc -std=gnu99 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c geodesic.c -o geodesic.o
/opt/rh/devtoolset-12/root/usr/bin/g++ -std=gnu++17 -I"/opt/R/4.3.1/lib/R/include" -DNDEBUG -I/usr/local/bin/gdal244/include -I/usr/include -I'/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c geos_methods.cpp -o geos_methods.o
geos_methods.cpp: In function ‘bool find_segments(GEOSContextHandle_t, std::vector<double>&, std::vector<double>&, std::vector<double>&, std::vector<double>&, std::vector<long unsigned int>&, std::vector<double>&, std::vector<double>&)’:
geos_methods.cpp:734:29: error: ‘GEOSSegmentIntersection_r’ was not declared in this scope; did you mean ‘GEOSIntersection_r’?
  734 |                         if (GEOSSegmentIntersection_r(hGEOSCtxt, x[i], y[i], x[i+1], cy[j+1], cx[j], cy[j], cx[j+1], cy[j+1], &ix, &iy) == 1) {
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                             GEOSIntersection_r
make: *** [geos_methods.o] Error 1
ERROR: compilation failed for package ‘terra’
* removing ‘/home/<sanitised>/R/x86_64-pc-linux-gnu-library/4.3/terra’
Warning in install.packages :
  installation of package ‘terra’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpBz3b6T/downloaded_packages’
Connected to your session in progress, last started 2025-Feb-10 20:40:46 UTC (11 minutes ago)

Thanks,

**Comment by rhijmans** [comment]
I fixed this in the development version, and you can install it with `remotes::install_github("rspatial/terra")`
The problem is that you have an older version of GEOS and I did not check for that. 
It is best to not ask new questions in closed issues as these easily get lost.

**Comment by Nishantha2006** [comment]
Thanks,
The documentation say it should work with GEOS version >= 3.4.0 - while we have 3.4.2. I'll try upgrading this and see if it helps.
I'll start a new conversation, if the problem remains after the GEOS upgrade.
Many thanks again.
