### ISSUE TITLE
Failing to install development version of terra

### ISSUE THREAD

**Issue by DavidDHofmann** [rspatial/terra#184]
Hi there!

I'm trying to install the latest development version of terra using `remotes::install_github()`. However, the installation fails with the following error:

```
gdalio.cpp: In function ‘std::__cxx11::string gdalinfo(std::__cxx11::string, std::vector<std::__cxx11::basic_string<char> >, std::vector<std::__cxx11::basic_string<char> >)’:
gdalio.cpp:345:63: error: expected ‘,’ or ‘;’ before ‘)’ token
  std::string out = "GDAL version >= 2.1 required for gdalinfo");
                                                               ^
/usr/lib/R/etc/Makeconf:177: recipe for target 'gdalio.o' failed
make: *** [gdalio.o] Error 1
ERROR: compilation failed for package ‘terra’
* removing ‘/home/david/R/x86_64-pc-linux-gnu-library/3.6/terra’
* restoring previous ‘/home/david/R/x86_64-pc-linux-gnu-library/3.6/terra’
```
I have installed the latest GDAL version for my system (GDAL: 3.0.4). Here's my `sessionInfo()`
```

R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 19.3

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=de_CH.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_CH.UTF-8        LC_COLLATE=de_CH.UTF-8    
 [5] LC_MONETARY=de_CH.UTF-8    LC_MESSAGES=de_CH.UTF-8   
 [7] LC_PAPER=de_CH.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_CH.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] ps_1.5.0          prettyunits_1.1.1 crayon_1.4.1      withr_2.4.1      
 [5] rprojroot_2.0.2   assertthat_0.2.1  R6_2.5.0          cli_2.3.1        
 [9] curl_4.3          remotes_2.2.0     rstudioapi_0.13   callr_3.5.1      
[13] tools_3.6.3       glue_1.4.2        compiler_3.6.3    processx_3.4.5   
[17] pkgbuild_1.2.0  
```
I assume it has something to do with me using R version 3.6. The installation worked on an other machine with R 4.0. I don't necessarily want to update R though, as I need to work with some deprecated packages. Any suggestions?

**Comment by rhijmans** [comment]
Thanks, fixed now. That code is only triggered when using a very old version of GDAL.

**Comment by DavidDHofmann** [comment]
Awesome! Installed perfectly fine now. Thank you!
