### ISSUE TITLE
compatibility problems with Redhat Linux?

### ISSUE THREAD

**Issue by VirginiaMorera** [rspatial/terra#360]
Hi, 

I've been trying to install terra in an RStudio server run by my institution and having issues that I think are related to GDAL, GEOS and PROJ libraries. I've been told by IT support to check whether the package has compatibility issues with Redhat Linux before they update anything. Can you please confirm? Below Sys.info()

                                  sysname                               release 
                                  "Linux"         "3.10.0-1160.25.1.el7.x86_64" 
                                  version                              nodename 
    "#1 SMP Tue Apr 13 18:55:45 EDT 2021"                             "rstudio" 
                                  machine                                 login 
                                 "x86_64"                             "unknown"

**Comment by Nowosad** [comment]
One suggestion could be updating your R version. R 3.6 is about 2.5 years old...

**Comment by rhijmans** [comment]
`error: no matching function for call to ‘regex_replace(` indeed suggests that you use an old compiler, that does not (fully) support the C++11 standard (the 11 stands for 2011).  You *may* have access to a newer compiler. For example, on my system I see 

```
module avail gcc
# gcc/4.5  gcc/4.7.3  gcc/4.9.3  gcc/5.5.0  gcc/6.3.1  gcc/7.2.0  gcc/7.3.0(default)  gcc/9.2.0
```

And I can do  
```
module load gcc/9.2.0
Module gcc/9.2.0 loaded
```

Likewise for R, by the way; although terra should compile with R/3.6.  It should also work well with 3.6, but I have not tested it recently (I might do that today and report back if I find something of note).
